### ISSUE TITLE
Link to language docs pages from templates

### ISSUE THREAD

**Issue by clstokes** [pulumi/templates#163]
The various language pages have details about how the runtimes work and available configuration options. The templates should include a link to these pages in the project yaml file to make them more discoverable.

For example, for the `aws-python` template (https://github.com/pulumi/templates/blob/master/aws-python/Pulumi.yaml):
```yaml
name: ${PROJECT}
description: ${DESCRIPTION}
# See https://www.pulumi.com/docs/intro/languages/python/ for more details and configuration options.
runtime: python 
template:
  description: A minimal AWS Python Pulumi program
  important: true
  config:
    aws:region:
      description: The AWS region to deploy into
      default: us-east-1
```
