### ISSUE TITLE
Generated YAML programs have four-space files, despite two-space templates

### ISSUE THREAD

**Issue by cnunciato** [pulumi/templates#361]
### What happened?

When I run `pulumi new aws-yaml`, for example, I get a program file with four-space formatting, despite that the template is defined with two-space indentation:

Source template:

```yaml
name: ${PROJECT}
description: ${DESCRIPTION}
runtime: yaml
template:
  description: A minimal AWS Pulumi YAML program
  important: true
  config:
    aws:region:
      description: The AWS region to deploy into
      default: us-east-1

resources:
  # Create an AWS resource (S3 Bucket)
  my-bucket:
    type: aws:s3:Bucket

outputs:
  # Export the name of the bucket
  bucketName: ${my-bucket.id}
```

Resulting program:

```yaml
name: yaml-test-2
description: A minimal AWS Pulumi YAML program
runtime: yaml
resources:
    # Create an AWS resource (S3 Bucket)
    my-bucket:
        type: aws:s3:Bucket
outputs:
    # Export the name of the bucket
    bucketName: ${my-bucket.id}
```

### Steps to reproduce

Run `pulumi new aws-yaml` and examine the contents of `Pulumi.yaml`.

### Expected Behavior

Pulumi.yaml uses two-space indentation, or at least indentation matching that of its source template file(s).

### Actual Behavior

It uses four-space indentation.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
